#!/usr/bin/with-contenv bash

exec 2>&1
chown -R tomcat8:tomcat8 /var/lib/tomcat8/
touch /var/lib/tomcat8/logs/catalina.out

mkdir -p /tmp/tomcat8-tmp 2>/dev/null

cd /var/lib/tomcat8

exec /usr/local/bin/gosu tomcat8 /usr/bin/java --illegal-access=permit \
    -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties \
    -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager \
    -Djava.awt.headless=true -Xmx128m -XX:+UseParallelGC \
    -classpath /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar \
    -Dcatalina.base=/var/lib/tomcat8 -Dcatalina.home=/usr/share/tomcat8 \
    -Djava.io.tmpdir=/tmp/tomcat8-tmp org.apache.catalina.startup.Bootstrap start
