#!/usr/bin/with-contenv bash
exec 2>&1
WD=${WIDTH:-1920}
HT=${HEIGHT:-1080}

exec /usr/local/bin/gosu nobody Xvnc4                                                             \
         ${DISPLAY:-:1}                                                                           \
        -geometry ${WD}x${HT}                                                                     \
        -depth ${VNC_DEPTH:-24}                                                                   \
        -rfbwait 30000                                                                            \
        -SecurityTypes None                                                                       \
        -rfbport 5901                                                                             \
        -bs                                                                                       \
        -ac                                                                                       \
	    -pn                                                                                       \
	    -fp /usr/share/fonts/X11/misc/,/usr/share/fonts/X11/75dpi/,/usr/share/fonts/X11/100dpi/   \
		-co /etc/X11/rgb                                                                          \
		-dpi ${VNC_DPI:-96}
