#!/usr/bin/with-contenv sh
##############################################################################
# Openbox service
##############################################################################
# Starts openbox as a service with the correct parameters
# The DISPLAY parameter can be overruled from the commandline startup command
# but that should never be necessary.
##############################################################################

exec 2>&1
DISP=${DISPLAY:-:1}
exec env DISPLAY=${DISP} HOME=/nobody /usr/local/bin/gosu nobody /usr/bin/openbox-session
sleep 1
