#!/command/s6-env bash
##############################################################################
# Tomcat service
##############################################################################
# Starts Tomcat as a service. Tomcat runs the Apache Guacamole Client
# Which enables the web gui.
##############################################################################

mkdir -p "/tmp/tomcat9-tmp" 2>/dev/null

/usr/bin/java \
    --add-opens=java.base/java.lang=ALL-UNNAMED \
    --add-opens=java.base/java.io=ALL-UNNAMED \
    --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED \
    -Djava.util.logging.config.file=/var/lib/tomcat9/conf/logging.properties \
    -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager \
    -Djava.awt.headless=true -Xmx128m -XX:+UseParallelGC \
    -classpath /usr/share/tomcat9/bin/bootstrap.jar:/usr/share/tomcat9/bin/tomcat-juli.jar \
    -Dcatalina.base=/var/lib/tomcat9 -Dcatalina.home=/usr/share/tomcat9 \
    -Djava.io.tmpdir=/tmp/tomcat9-tmp org.apache.catalina.startup.Bootstrap start
