#!/command/s6-env bash
##############################################################################
# Openbox service
##############################################################################
# Starts openbox as a service with the correct parameters
# The DISPLAY parameter can be overruled from the commandline startup command
# but that should never be necessary.
##############################################################################

DISP=${DISPLAY:-:1}
DISPLAY=${DISP} HOME=/nobody /usr/sbin/gosu nobody /usr/bin/openbox-session
sleep 1
